export const categories = {
  HEALTH_SPORTS: 'Health & Sports',
  FINANCE_INVESTMENTS: 'Finance & Investments',
  RELATIONSHIPS: 'Relationships',
  BUSINESS_CAREER: 'Business & Career',
  SPIRITUALITY: 'Spirituality',
  SEXUALITY: 'Sexuality',
  ENTERTAINMENT: 'Entertainment',
  COOKING_GASTRONOMY: 'Cooking & Gastronomy',
  LANGUAGES: 'Languages',
  LAW: 'Law',
  APPS_SOFTWARE: 'Apps & Software',
  LITERATURE: 'Literature',
  HOME_CONSTRUCTION: 'Home & Construction',
  PERSONAL_DEVELOPMENT: 'Personal Development',
  FASHION_BEAUTY: 'Fashion & Beauty',
  ANIMALS_PLANTS: 'Animals & Plants',
  EDUCATION: 'Education',
  HOBBIES: 'Hobbies',
  DESIGN: 'Design',
  INTERNET: 'Internet',
  ECOLOGY_ENVIRONMENT: 'Ecology & Environment',
  MUSIC_ARTS: 'Music & Arts',
  INFORMATION_TECHNOLOGY: 'Information Technology',
  DIGITAL_ENTREPRENEURSHIP: 'Digital Entrepreneurship',
  OTHER: 'Other',
} as const
